#!/bin/bash
# Run all dotfiles installers.

export DOTFILES=$HOME/.dotfiles

# find the installers and run them iteratively
#find . -name install.sh1 | while read installer ; do sh -c "${installer}" ; done
find $DOTFILES -name install.sh | while read installer ; 
                                  do 
                                    echo "${installer}" ;
				    ${installer} ;
				  done
