# stylize your powerlevel9k prompt
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_HISTORY_BACKGROUND='green'

# dir
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

#multiline
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{red} \Uf1d0 %f %F{yellow
}❯ "

#prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=false

# left_prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)

# right prompt
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history virtualenv)
